### ISSUE TITLE
crashes in production mode

### ISSUE THREAD

**Issue by Gigadoc2** [ironjan/klausurtool-ror#12]
While experimenting over at https://github.com/Gigadoc2/klausurtool-ror/tree/docker, i tried running the tool with `RAILS_ENV=production` (as opposed to `RAILS_ENV=development`, the default), which resulted in the application becoming very unstable.

All pages except for */ausleihe* only generate the following error message:
![error](https://cloud.githubusercontent.com/assets/1494790/12541865/5b04b042-c31c-11e5-8c9c-d946f459c2b5.png)
And */ausleihe* itself looks somewhat broken:
![bildschirmfoto vom 2016-01-25 04-00-25](https://cloud.githubusercontent.com/assets/1494790/12541886/8fdb1892-c31c-11e5-8847-128c2cff6d7e.png)

There are a lot of warnings about something not found in the log:
[production.log.txt](https://github.com/ironjan/klausurtool-ror/files/102733/production.log.txt)

Maybe something is only defined for the *development* mode?

**Comment by Gigadoc2** [comment]
I guess the css and javascript is not "found" because rails wants us to serve static content via the web server.

However there are still errors about not finding relevant tables, even though i initialized the database with rake db:schema:load (and it works perfectly with `RAILS_ENV=development`)

**Comment by ironjan** [comment]
```rake db:schema:load``` will initialize a database for development mode. For deploying the klausurtool I would recommend to dump the database used right now, use the converter to convert it and then rename it to production.db (see private chat).

```rake db:schema:load RAILS_ENV=production``` alternatively will create a production database (should only be done once; after that rake db:migrate should be used).

The assets are served by rails (see PR) and must be pre-compiled (and added to git) on local machines.
