### ISSUE TITLE
No Back/Start-Button in the DetailsView

### ISSUE THREAD

**Issue by Stormforge** [ironjan/klausurtool-ror#150]
In the Detail-View is no way to come back to the Start-View or to the Search-View

**Comment by ironjan** [comment]
Please include the URL or describe the detail view you are seeing. Also please mention of this is about the development version or the system currently running live.

**Comment by ironjan** [comment]
@Stormforge, please describe how you get to the detail screen that has this problem.

**Comment by Stormforge** [comment]
First you switch to "Inhalt(e)" then click on the "Ordner". This is the detail screen I mean.

**Comment by ironjan** [comment]
**Steps to reproduce (in development):**

1. Go to http://0.0.0.0:3000/ausleihe/exams
2. Click on one of the folder links

**What happens:**

You are redirected to the admin area, e.g. http://0.0.0.0:3000/admin/old_folders/175

**What should happen instead:**

The ausleihe folder detail screen should be shown.

**Additional information:**

The links on http://0.0.0.0:3000/ausleihe/folders are working as expected. It seems that the wrong path-reference is used.

**Comment by ironjan** [comment]
**Snippet: old_folder_instances/_instances_table.html.erb**

 * Working correctly

```ruby
<% if controller_name == "ausleihe" %>
<%= link_to i.old_folder.title, ausleihe_folder_path(i.old_folder) %>
<% elsif controller_name == "old_folder_instances" %>
<%= link_to i.old_folder.title, i.old_folder %>
<% end %>
```

**Snippet: old_exams/_exams_table.html.erb**

* Always links to admin-area

```ruby
<td><%= link_to e.old_folder.title, e.old_folder %></td>
```
