### ISSUE TITLE
"Change rejected" for editing folder group

### ISSUE THREAD

**Issue by sandwm** [ironjan/klausurtool-ror#167]
## How does this problem happen?
 1. Login
 2. Go to http://ausleihe.fachschafts.website/internal/admin/old_folders/100
 3. Click "Edit" ("Bearbeiten")
 4. Change content type (maybe others) or leave everything as is

## What does happen?

> The change you wanted was rejected.
> Maybe you tried to change something you didn't have access to.
> If you are the application owner check the logs for more information.

Check e.g. the logs for 2016-04-16 19:00:40.

**Comment by ironjan** [comment]
The log states 

```
Apr 16 18:32:35 fsmi-relentless docker[30626]: W, [2016-04-16T16:32:35.698189 #12]  WARN -- : Can't verify CSRF token authenticity
Apr 16 18:32:35 fsmi-relentless docker[30626]: I, [2016-04-16T16:32:35.698524 #12]  INFO -- : Completed 422 Unprocessable Entity in 1ms (ActiveRecord: 0.0ms)
Apr 16 18:32:35 fsmi-relentless docker[30626]: F, [2016-04-16T16:32:35.700139 #12] FATAL -- :
Apr 16 18:32:35 fsmi-relentless docker[30626]: ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
```

Is your browser rejecting cookies? All forms include a [CSRF Token](http://guides.rubyonrails.org/security.html#cross-site-request-forgery-csrf) by default that is valid until the session expires. By default, Rails uses a session cookie to enable CSRF.

This issue could only be reproduced by setting my browser to reject cookies.

**Comment by sandwm** [comment]
Yes, my browser blocked cookies. Enabling them for this domain solves the issue. Looks like a hint in the error message should be all that's needed.

**Comment by ironjan** [comment]
Moved extending the 401-page to #170
