### ISSUE TITLE
Add support for barcode scanner

### ISSUE THREAD

**Issue by ironjan** [ironjan/klausurtool-ror#22]
*Old tool:*
* scan something in lending form or returning form
* focus automatically moves to next field

*current implementation:*
* focus stays on field
* barcode scanner does not have any advantage

*probable cause:* 
Old tool had JavaScript that moved the focus after a scan was made. Probably line-break or something similar is placed at the end of scanned values.

**Comment by sandwm** [comment]
The barcode scanner seems to place a "Return" keyboard input after the scanned input. Test it e.g. in a textarea (start page) or a texteditor.

Pressing enter in the lending form also shows no reaction, if the form is not complete, but commits if complete. The scanner also automatically commits this way if used on the last empty field – not very nice if you wanted to check the input data before committing.

The "Return" should be replaced by a "Tab", fixing the above issues (apart from "no error message for incomplete form") – but only for the barcode scanner "Return", not the real keyboard. Maybe use timings as a heuristic? I didn't take a look into the old JavaScript for focus movement after scanning.

**Comment by ironjan** [comment]
The old code for that function could be this one: https://git.cs.upb.de/fsmi/klausurtool-og/blob/master/ausleihe/src/tool/action.php#L84

From a quick look the code seems - simplified and pseudo - like
```
// Enter 
form.submit = {
  for every field in form:
    set focus to field
    if field is invalid, don't submit // return false
  otherwise all fields are valid, submit // return true
}
```

It may be that a similar (but less hacky) solution is necessary if midori can't be updated to a version that supports html5 form validation out of the box or replaced by another browser that does. 

*Notes*: http://blueashes.com/2013/web-development/html5-form-validation-fallback/

**Comment by ironjan** [comment]
Further tests have confirmed: the current browser **partly** supports form validation, i.e. incomplete forms are not submitted, but no user notification is given.

**Comment by ironjan** [comment]
The broken barcode scanner functionality is caused by midori missing form validation. See #92
