### ISSUE TITLE
Fetch name via IMT Login

### ISSUE THREAD

**Issue by sandwm** [ironjan/klausurtool-ror#44]
Show who borrowed a folder when taking it back (/ausleihe/returning_form), so the correct deposit (e.g. matching ID) can be found.

Since IMT login names are used, you might want to use
`ldapsearch -x -b 'o=upb,c=de' -H 'ldap://ldap.uni-paderborn.de' -LLL uid=$USER cn`
to show IMT login and real name.

**Comment by ironjan** [comment]
Since I've got an exam on friday, this probably must wait until ```0.0.11```. Probably useful for implementation: http://stackoverflow.com/questions/334519/ldap-through-ruby-or-rails

**Comment by ironjan** [comment]
"Showing name" moved to #45 to keep things clear

**Comment by ironjan** [comment]
```results=ldap.search(base: 'o=upb,c=de', filter: Net::LDAP::Filter.eq("uid", imtLogin)).first.gecos.first```
#45 may be dropped in favor of this (Assumed that this issue be harder)
