### ISSUE TITLE
List of folders with broken encodings is incomplete

### ISSUE THREAD

**Issue by ironjan** [ironjan/klausurtool-ror#48]
It does not show all folders with broken encodings, e.g. the following are missing:

* EinfÃ¼hrung in Berechenbarkeit, KomplexitÃ¤t und formale Sprachen 
* BrÃ¼ckenkurs Mathematik 

There are some more missing. Perhaps it's easier to fix these folders and remove the then irrelevant function.

**Comment by Gigadoc2** [comment]
I'll try to fix the folders in my testing environment and then report back.

**Comment by ironjan** [comment]
Seems that it was a copy-paste mistake. Doh! https://github.com/ironjan/klausurtool-ror/blob/master/app/controllers/old_folders_controller.rb#L15 searches for exams. Should probably be something like

```ruby
@old_folders = OldFolder.all
@old_folders = @old_folders.select { |folder| folder.title[regex]}
```
