### ISSUE TITLE
"No LDAP connection" errors

### ISSUE THREAD

**Issue by sandwm** [ironjan/klausurtool-ror#63]
/ausleihe/lent shows "Keine Verbindung zum LDAP", although the command I mentioned in #44 works when run on the webserver (fsmi@guarana).

**Comment by ironjan** [comment]
The problem was discovered and discussed yesterday with gigadoc. It seems that relentless -the server the tool is running on - does not have anonymous LDAP access. Investigations will be done today.

**Comment by ironjan** [comment]
A manual test discovered that authentification fails, even when passing an imt login. It may be, that relentless is not part of the imt infrastructure and therefore does not get access to the LDAP. #45 will be re-opened until this is fixed.

**Comment by sandwm** [comment]
Not being able to use the LDAP is a known problem on relentless (although not as pressing as to get somebody to fix it until now). I thought the tool was running on guarana (now that you mention it – gigadoc2 told me that relentless is used a week or two ago).

It might be possible to enable LDAP access on relentless. Thinking of:
 * mail to IMT or
 * ssh tunnel: relentless -> LDAP-capable host -> ldap.upb.de

Task for me or Gigadoc2 (as RBFSMI members) I think. I will see if I can get to it today or tomorrow.

**Comment by sandwm** [comment]
Workaround using `/etc/hosts` and ssh tunnel in effect. I'll send a mail to the IMT to ask if we can get regular LDAP access, but I'm not sure if we need some special abilities for our other services. I'm going to coordinate with @Gigadoc2 on this.

**Comment by ironjan** [comment]
The workaround changed the error to Connection refused. Stacktrace below.

```
Net::LDAP.new(host: 'ldap.uni-paderborn.de').bind
Deprecation warning: Net::LDAP::ConnectionRefused will be deprecated. Use Errno::ECONNREFUSED instead.
Net::LDAP::ConnectionRefusedError: Connection refused - connect(2) for 127.0.0.1:389
	from /usr/local/bundle/gems/net-ldap-0.14.0/lib/net/ldap/connection.rb:63:in `open_connection'
	from /usr/local/bundle/gems/net-ldap-0.14.0/lib/net/ldap/connection.rb:679:in `socket'
	from /usr/local/bundle/gems/net-ldap-0.14.0/lib/net/ldap.rb:1311:in `new_connection'
	from /usr/local/bundle/gems/net-ldap-0.14.0/lib/net/ldap.rb:854:in `block in bind'
	from /usr/local/bundle/gems/net-ldap-0.14.0/lib/net/ldap/instrumentation.rb:19:in `instrument'
	from /usr/local/bundle/gems/net-ldap-0.14.0/lib/net/ldap.rb:848:in `bind'
	from (irb):3
	from /usr/local/bundle/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in `start'
	from /usr/local/bundle/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/bundle/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /usr/local/bundle/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/bundle/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /home/klausurtool/klausurtool-ror/bin/rails:9:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
	from /usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'irb(main):004:0> 
```

**Comment by Gigadoc2** [comment]
SSH died, i've restarted it as ldap-ssh-tunnel.service.

Lookup seems to be working for the moment.

**Comment by sandwm** [comment]
SSH died again ("connection lost"). I changed the service file to Restart=always. It's working again for now. Mail to the IMT was sent yesterday – no answer till now.

@Gigadoc2: I moved it to /etc/systemd/system/ldap-tunnel.service because systemd didn't reload it in /run/ (even with systemctl daemon-{reload,reexec}).

**Comment by ironjan** [comment]
IMT-Login has been stable for some time therefore I'll close this issue.

For reference: #76 will change the behavior of fetching names (they will be fetched on lending and saved in the DB).
