### ISSUE TITLE
Migrate to MySQL

### ISSUE THREAD

**Issue by ironjan** [ironjan/klausurtool-ror#64]
1. Go to http://0.0.0.0:3000/ausleihe/folders?utf8=%E2%9C%93&search=%C3%BCber&commit=Suche
2. The page should list "Übersetzer (Compiler)"

**Comment by ironjan** [comment]
The current workaround introduces the problem of "finding too many results" but at least all umlaut results are found. The cause of the problem is that SQLITE does *not* support case conversion for UTF-8. There are two possibilities:

* Replace SQLITE by MySQL as described in http://stackoverflow.com/questions/1670154/convert-a-ruby-on-rails-app-from-sqlite-to-mysql (tested, but did not work. The database accumulated invalid values over time and when inserting the data into mysql, the values are validated against their datatype).
* Add ICU extension to SQLITE as described in http://stackoverflow.com/questions/611459/how-to-sort-text-in-sqlite3-with-specified-locale

The first solution would be preferable because it would prevent another accumulation of invalid data.

**Comment by Gigadoc2** [comment]
I would have proposed the switch to MySQL anyway, so let's roll with it. I'll have a look at converting and repairing the database.

**Comment by ironjan** [comment]
The blocking thing seem to be dates for now (0000-00-00, 2010-10-00,...). Many inconsistent workarounds have been introduced over time for "no date given". 

old_exams_controller already includes a " read and fix " for the edit exam screen. This was done so that these values can be fixed over time and could easily moved to the model.

Or alternatively we can just execute find and replace (/0000/1970/ and /00/01/) on the database. That way the dates are fixed quickly. 

The "broken utf-8 strings" are non-blocking for moving to MySQL

**Comment by Gigadoc2** [comment]
For me, MySQL only refuses to accept dates with day and month switched (american style), but not "empty" or even "partially empty" dates. And in our Database there are only two such dates (14811 and 16427), so I corrected them and was able to load everything into MySQL.

However, I used the gem 'mysql2' (i could not get 'mysql' [to work](https://stackoverflow.com/questions/5286117/incompatible-character-encodings-ascii-8bit-and-utf-8)), and I had to set `cast: false` to actually use the new database (see https://stackoverflow.com/questions/16389313/how-to-gracefully-handle-mysql2error-invalid-date-in-activerecord).
Also, I don't know how all of this mixes with your "read and fix" (or anything else actually).

So, is 'mysql2' the right gem for this, and what are the implications of `cast:false` in `config/database.yml`?

**Comment by ironjan** [comment]
With ```cast: true``` (probably default), strings in a date format (afaik ISO-like, e.g. yyyy-mm-dd) are converted to the ```Time```-class. If the date in the database is wrong, this will fail in the 'mysql2' gem. The "read and fix" would not work in that case because it would crash before that point.

If ```cast: false```, no such casting occurs. It may be, that the ```date``` fields are set to ```nil``` in that case and the fix works as expected. 

Did you create a branch for the MySQL test?

For "read and fix" see c28a23d

**Comment by Gigadoc2** [comment]
Does the 'sqlite3' gem not cast at all then?

I'm not sure if anything I'm doing makes sense, but [here,](https://github.com/ironjan/klausurtool-ror/tree/64-migrate-to-mysql) have a branch :D

**Comment by ironjan** [comment]
Yeah, seems like the sqlite-gem doesn't do any casts on its own and it let's rails handle the casts, I.e. every field is returned as the string that was saved in the database. if the rails cast fails, rails just puts nil as a result, but for every $field there's a $field_before_your_cast to access what was read from db.

The mysql2 gem tries these casts after reading and throws exceptions. I'll checkout your branch later and try if ```cast: false``` means "do it like sqlite".

**Comment by ironjan** [comment]
When I tried to migrate on my local machine, there were some errors about failing foreign-key constraints. It may be, that we have to reorder the datasets in the data.yml before importing them again. 

Also, we'll have to check if all migrations work - or if there are some that are "sqlite"-specific and need to be archived.
